title: CypherNyct
description: "Ciberseguridad · Writeups · Apuntes · CTFs"
author: CypherNyct
url: "https://cyphernyct.github.io"
baseurl: ""

markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

kramdown:
  input: GFM
  syntax_highlighter: rouge

collections:
  writeups:
    output: true
    permalink: /writeups/:path/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "writeups"
    values:
      layout: "post"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
